name: deploy

on:
  push:
    branches:
      - 'master/.devcontainer/**'
      - 'master/.github/**'
      - 'master/packages/web/**'
      - 'master/package.json'
      - 'master/yarn.lock'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.2'
        
      - name: Build web-app
        run: |
          yarn ci
          cd ./packages/web && yarn run build
        
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build