name: deploy

on:
  push:
    branches:
      - master
    paths:
      - 'packages/web/**'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.14.2'
      - name: Build web-app
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn run build packages/web/
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build